# Total Revenue

SELECT ROUND(SUM(TOTAL_AMOUNT),2) AS TOTAL_REVENUE
FROM BLINKIT_FINAL;

# Total Orders 
SELECT count(distinct ORDER_ID) AS TOTAL_ORDERS
FROM BLINKIT_FINAL;

# TOTAL CUSTOMERS
SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM BLINKIT_FINAL;

# AVERAGE ORDER VALUE
SELECT ROUND(AVG(TOTAL_AMOUNT),2) AS AVERAGE_ORDER_VALUE
FROM BLINKIT_FINAL;

# REVENUE BY CATEGORY
SELECT CATEGORY,ROUND(SUM(TOTAL_AMOUNT),2) AS CAT_WISE_REVENUE
FROM BLINKIT_FINAL
GROUP BY CATEGORY
ORDER BY CAT_WISE_REVENUE DESC;

# TOP 10 PRODUCTS
SELECT PRODUCT_NAME,ROUND(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM BLINKIT_FINAL
GROUP BY PRODUCT_NAME
ORDER BY REVENUE DESC
LIMIT 10;

# REVENUE BY CUSTOMER SEGMENT
SELECT CUSTOMER_SEGMENT,ROUND(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM BLINKIT_FINAL
GROUP BY CUSTOMER_SEGMENT
ORDER BY REVENUE DESC;

# PAYMENT METHOD ANALYSIS
SELECT PAYMENT_METHOD, COUNT(*) AS ORDERS,ROUND(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM BLINKIT_FINAL
GROUP BY PAYMENT_METHOD;


# DELIVERY PERFORMANCE
SELECT DELIVERY_STATUS,COUNT(*) AS ORDERS
FROM BLINKIT_FINAL
GROUP BY DELIVERY_STATUS;


# SENTIMENT ANALYSIS
SELECT SENTIMENT,COUNT(*) AS FEDDBACK_COUNT
FROM BLINKIT_FINAL
GROUP BY SENTIMENT;


# MONTHLY REVENUE TREND
SELECT DATE_FORMAT(ORDER_DATE ,'%Y-%M') AS MONTH, ROUND(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM BLINKIT_FINAL
GROUP BY DATE_FORMAT(ORDER_DATE, '%Y-%M')
ORDER BY DATE_FORMAT(ORDER_DATE, '%Y-%M');


# AVERAGE RATING BY DELIVERY STATUS
SELECT DELIVERY_STATUS,ROUND(AVG(RATING),2) AS AVG_RATING
FROM BLINKIT_FINAL
GROUP BY DELIVERY_STATUS;


# TOP BRANDS
SELECT BRAND,round(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM BLINKIT_FINAL GROUP BY BRAND
ORDER BY REVENUE DESC 
LIMIT 10;

